"""
Neo4j compiler — generates CYPHER queries for creating ontology data in Neo4j.

Output is a string containing a sequence of CYPHER statements (CREATE,
MERGE, etc.) that can be executed against a Neo4j database.
"""

from __future__ import annotations

import time

from .compiler import CompilationResult, Compiler
from ..ontology_model.types import Ontology


class Neo4jCompiler(Compiler):
    """Compiles an Ontology into CYPHER query strings.

    Produces MERGE statements for nodes and CREATE statements for
    relationships, compatible with Neo4j 4.x / 5.x.

    Parameters
    ----------
    name : str
        Optional label.
    """

    def __init__(self, name: str = "") -> None:
        super().__init__(name=name or "Neo4jCompiler")

    @staticmethod
    def _escape_prop(value: object) -> str:
        if value is None:
            return "null"
        if isinstance(value, bool):
            return "true" if value else "false"
        if isinstance(value, (int, float)):
            return str(value)
        s = str(value)
        escaped = s.replace("\\", "\\\\").replace("'", "\\'")
        return f"'{escaped}'"

    @staticmethod
    def _props_to_cypher(props: dict) -> str:
        if not props:
            return "{}"
        items = []
        for k, v in props.items():
            items.append(f"{k}: {Neo4jCompiler._escape_prop(v)}")
        return "{" + ", ".join(items) + "}"

    def compile(self, ontology: Ontology) -> CompilationResult:
        """Generate CYPHER statements from *ontology*.

        Returns
        -------
        CompilationResult
            ``.output`` is a string containing CYPHER statements separated
            by newlines.
        """
        start = time.perf_counter()
        lines: list[str] = []
        lines.append("// Generated by Neo4jCompiler")
        lines.append(f"// Objects: {len(ontology.objects)}, Relations: {len(ontology.relations)}")
        lines.append("")

        lines.append("CREATE CONSTRAINT IF NOT EXISTS FOR (n:OntologyObject) REQUIRE n.id IS UNIQUE;")
        lines.append("")

        for obj_id, obj in ontology.objects.items():
            labels = ["OntologyObject"]
            safe_type = "".join(c for c in obj_id if c.isalnum() or c == "_")
            if safe_type:
                labels.append(safe_type)
            label_str = ":".join(labels)
            props = {
                "id": obj_id,
                "name": obj.name,
            }
            if obj.parent_id:
                props["parent_id"] = obj.parent_id
            props_str = self._props_to_cypher(props)
            lines.append(f"MERGE (n:{label_str} {props_str});")

            for prop in obj.properties:
                lines.append(
                    f"MATCH (n:OntologyObject {{id: '{obj_id.replace(chr(39), chr(39)*2)}'}})"
                )
                safe_key = "".join(c for c in prop.name if c.isalnum() or c == "_") or "prop"
                lines.append(
                    f"SET n.{safe_key} = {self._escape_prop(prop.default)};"
                )

        lines.append("")

        for rel_id, rel in ontology.relations.items():
            src = rel.source_type.replace("'", "\\'")
            tgt = rel.target_type.replace("'", "\\'")
            rname = "".join(c for c in (rel.name or rel_id) if c.isalnum() or c == "_")
            if not rname:
                rname = "RELATED_TO"
            props = {"id": rel_id}
            for prop in rel.properties:
                safe_key = "".join(c for c in prop.name if c.isalnum() or c == "_") or "prop"
                props[safe_key] = prop.default
            props_str = self._props_to_cypher(props)
            lines.append(
                f"MATCH (a:OntologyObject {{id: '{src}'}}), "
                f"(b:OntologyObject {{id: '{tgt}'}})\n"
                f"CREATE (a)-[r:{rname} {props_str}]->(b);"
            )

        output = "\n".join(lines)
        elapsed = (time.perf_counter() - start) * 1000

        return CompilationResult(
            output=output,
            format_name="neo4j_cypher",
            compilation_time_ms=elapsed,
            metadata={
                "object_count": len(ontology.objects),
                "relation_count": len(ontology.relations),
            },
        )
